import { 
    ID_PRODUCT_STRIP_SUBSCRIPTION, 
    TIME_FOR_REVALIDATE, 
    TIME_FOR_REVALIDATE_AUTH } from "./const";

export { 
    ID_PRODUCT_STRIP_SUBSCRIPTION,
    TIME_FOR_REVALIDATE, 
    TIME_FOR_REVALIDATE_AUTH 
}